name: build_llvm

on:
  workflow_dispatch:
    inputs:
      hostArch:
        description: 'Arch of build host'
        required: false
        default: x64
        type: choice
        options:
          - x86
          - x64
      targetArch:
        description: 'Arch of target to build'
        required: true
        default: x64
        type: choice
        options:
          - x86
          - x64
      llvmTargets:
        description: "llvm targets to build (use ';' to split)"
        type: string
        default: X86
        required: false

  workflow_call:
    inputs:
      host-arch:
        description: the host arch to build
        type: string
        default: x64
        required: false
      target-arch:
        description: the target arch to build
        type: string
        default: x64
        required: true
      llvm-targets:
        description: llvm targets to build (use ';' to split)
        type: string
        default: X86
        required: false
env:
  llvm_ver: 13.0.0
  target_arch: x64
  host_arch: x64
  llvm_targets: X86
  modifier: 'none'
jobs:
  build_prepare:
    name: Prepareing before build
    runs-on: ubuntu-latest
    steps:
      - name: Processing workflow call
        if: ${{ github.event_name == 'workflow_call' }}
        run: |
          echo ::group::workflow_call param preparing
          echo ::endgroup::
        env:
          modifier: 'workflow_call'
          target_arch: ${{ inputs.target-arch }}
          host_arch: ${{ inputs.host-arch }}
          llvm_targets: ${{ inputs.llvm-targets }}

      - name: Processing workflow dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo ::group::workflow_dispatch param preparing
          echo ::endgroup::
        env:
          modifier: 'workflow_dispatch'
          target_arch: ${{ github.event.inputs.targetArch }}
          host_arch: ${{ github.event.inputs.hostArch }}
          llvm_targets: ${{ github.event.inputs.llvmTargets }}

      - name: Showing Environment
        run: |
          echo ${{github.event_name}}
          cat ${{github.env}} 

  build:
    name: Build llvm on Windows with Clang
    needs:
      - build_prepare
    runs-on: windows-latest
    steps:
      - name: Install dependency
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install cmake ninja vswhere

      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
        with:
          sdk-version: 19041

      # replaces git clone with actions/checkout
      # arg of command:
      # --branch llvmorg-13.0.0 --depth 1 https://github.com/llvm/llvm-project.git
      - uses: actions/checkout@v2
        with:
          repository: 'llvm/llvm-project'
          ref: 'llvmorg-${{env.llvm_ver}}'
          fetch-depth: '1'

      - name: Build llvm clang+lld
        run: |
          $vsPath = (vswhere -latest -property installationPath)
          Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=${{env.target_arch}} -host_arch=${{env.host_arch}} -winsdk=10.0.19041.0"
          
          echo "::group::configure by cmake (modified by${{env.modifier}})"
          $Env:CC = "cl"
          $Env:CXX = "cl"
          cmake -Bbuild-clang+lld -GNinja `
          -DCMAKE_SYSTEM_VERSION="10.0.19041.0" `
          -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL `
          -DCMAKE_BUILD_TYPE=Release `
          -DCPACK_GENERATOR=ZIP `
          -DCPACK_PACKAGE_NAME="llvm.clang+lld.${{env.target_arch}}" `
          -DLLVM_USE_CRT_RELEASE=MT `
          -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON `
          "-DCMAKE_INSTALL_PREFIX=$pwd\\prefix" `
          -DLLVM_TARGETS_TO_BUILD="${{env.llvm_targets}}" `
          -DLLVM_ENABLE_PROJECTS="clang;lld" llvm
          echo "::endgroup::"
          
          echo "::group::building clang"
          cmake --build build-clang+lld --clean-first -- -j 16
          echo "::endgroup::"

      - name: Build llvm lld
        run: |
          $vsPath = (vswhere -latest -property installationPath)
          Import-Module (Join-Path $vsPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll")
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation -DevCmdArguments "-arch=${{env.target_arch}} -host_arch=${{env.host_arch}} -winsdk=10.0.19041.0"
          
          echo "::group::configure by cmake"
          $Env:CC = "cl"
          $Env:CXX = "cl"
          cmake -Bbuild-lld -GNinja `
          -DCMAKE_SYSTEM_VERSION="10.0.19041.0" `
          -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL `
          -DCMAKE_BUILD_TYPE=Release `
          -DCPACK_GENERATOR=ZIP `
          -DCPACK_PACKAGE_NAME="llvm.lld.${{env.target_arch}}" `
          -DLLVM_USE_CRT_RELEASE=MT `
          -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON `
          "-DCMAKE_INSTALL_PREFIX=$pwd\\prefix" `
          -DLLVM_TARGETS_TO_BUILD="${{env.llvm_targets}}" `
          -DLLVM_ENABLE_PROJECTS="lld" llvm
          echo "::endgroup::"
          
          echo "::group::building lld"
          cmake --build build-lld --clean-first -- -j 16
          echo "::endgroup::"

      - name: Package llvm
        run: |
          cmake --build build-clang+lld --target package
          cmake --build build-lld --target package

      - name: Content list
        run: |
          echo "::group::clang+lld"
          ls ./build-clang+lld
          echo "::endgroup::"

          echo "::group::lld"
          ls ./build-lld
          echo "::endgroup::"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: llvm
          path: |
            build-clang+lld/llvm.clang+lld.*.zip
            build-lld/llvm.lld*.zip
          retention-days: 5
